### ISSUE TITLE
## Check if the old archive file exists, if it does, delete it.

### ISSUE THREAD

**Issue by non7top** [chuguniy/bash-data-compression#1]
1. ## Check if the old archive file exists, if it does, delete it.
   если создание нового архива завершится с ошибкой, улыбаемся и машем, имея на руках 0 валидных бэкапов?

**Comment by chuguniy** [comment]
Скрипт изначально писался для определённых целей (архивация директории со снэпшотом системы). Создаётся архив, потом этот архив загружается в облако. Так, как сервис закачивающий архив ссылается на один и тот же файл, то нужно удалить, а потом создать его заново, чтоб он загрузил его. При всём этом данные не теряются, потому как изначальная директория остаётся!

В следующей версии скрипта добавлю функционала, учту и ваше пожелание! Будет готов на днях.

**Comment by chuguniy** [comment]
Добавил копирование и ротацию старых архивов.
